### ISSUE TITLE
Only Errors

### ISSUE THREAD

**Issue by MJMODZZ** [Callumgm/Clean-GUI-Template#5]
I tryed to compile but only got errors.

- Using VS2019
- Both Dll´s added
- Nedded C# packages installed

**Comment by MJMODZZ** [comment]
I just fixed it by myself, fix is avaiable on my github

**Comment by Callumgm** [comment]
Thanks for the fix, also wanna collab on this to make it POP a bit more?

**Comment by MJMODZZ** [comment]
> Thanks for the fix, also wanna collab on this to make it POP a bit more?

Yes if you Mark me as contibutor i could fix it in this reposetory.
